# Generated by Django 2.2 on 2021-07-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users_app.Room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users_app.User')),
            ],
        ),
    ]
