# Generated by Django 2.2 on 2021-07-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_superrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperRelation',
        ),
    ]
